# Site settings
title: Elevated Computer Specialists
email: contact@elevatedcs.net
zendesk_email: support@elevatedcs.net
phone: 719.297.7995
phone-link: tel:+17192977995
copyright-year: 2015
tag_line: ECS is a vendor-neutral IT managed service provider dedicated to the success of its clients.


seo:
  description: Elevated Computer Services
  title: Elevated Computer Services
  keywords: technology, IT, information technology, servers


url: http://www.elevatedcomputerspecialists.com/


# Build settings
markdown: kramdown
