# Site settings
title: Elevated Computer Specialists
email: contact@elevatedcs.net
zendesk_email: support@elevatedcs.net
phone: 719.297.7995
phone-link: tel:+17192977995
copyright-year: 2015
tag_line: ECS is a vendor-neutral IT managed service provider dedicated to the success of its clients.


seo:
  description: Elevated Computer Specialists is a vendor-neutral IT managed service provider dedicated to the success of its clients.
  title: Elevated Computer Specialists | Colorado Springs, CO
  keywords: technology, IT, information technology, servers, managed services provider, colorado springs, CO, IT support, IT consulting, denver


url: http://www.elevatedcomputerspecialists.com/


# Build settings
markdown: kramdown
